#ifndef LIVEKIT_CXX_SDK_INCLUDE_ABC_REFERENCE_COUNTER
#define LIVEKIT_CXX_SDK_INCLUDE_ABC_REFERENCE_COUNTER

#pragma once

#include "reference_counter_decl.h"

#endif // LIVEKIT_CXX_SDK_INCLUDE_ABC_REFERENCE_COUNTER
