#ifndef LIVEKIT_CXX_SDK_INCLUDE_ABC_REFERENCE_COUNTER_FWD_DECL
#define LIVEKIT_CXX_SDK_INCLUDE_ABC_REFERENCE_COUNTER_FWD_DECL

#pragma once

namespace abc
{
class RefCounterImpl;
class RefCounter;
}

#endif // LIVEKIT_CXX_SDK_INCLUDE_ABC_REFERENCE_COUNTER_FWD_DECL
