aux_source_directory(./proto PROTO_SRCS)
aux_source_directory(./ FFI_SRCS)
add_library(${LIVEKIT_CXX_FFI_LIBRARY} ${FFI_SRCS} ${PROTO_SRCS})
target_link_libraries(${LIVEKIT_CXX_FFI_LIBRARY} PRIVATE protobuf)

# add_subdirectory(proto)
# aux_source_directory(./ FFI_SRCS)
# add_library(${LIVEKIT_CXX_FFI_LIBRARY} ${FFI_SRCS})
# target_link_libraries(${LIVEKIT_CXX_FFI_LIBRARY} PRIVATE ${LIVEKIT_CXX_PROTO_LIBRARY})
# target_link_libraries(${LIVEKIT_CXX_FFI_LIBRARY} PRIVATE ${PROTOBUF_LIBRARY})
# target_include_directories(${LIVEKIT_CXX_FFI_LIBRARY} PRIVATE ${PROTOBUF_INCLUDE_DIR})
